name: PortfolioEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - sympy=1.11.1
  - numpy=2.4.3
  - scipy=1.17.1
  - matplotlib=3.10.8
  - jupyterLab=4.5.6
  - control=0.10.2
  - imageio=2.6.1
  - pyvista=0.47.1
  - pygame=2.6.1